'use client';

import ClientHeader from "@/components/ClientHeader";
import { ApolloWrapper } from "@/lib/ApolloWrapper";
import { Work_Sans } from "next/font/google";
import Contact from "@/components/Contact";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Sora } from "next/font/google";
import { Provider } from 'react-redux';
import { store } from '@/redux/store';
import Chat from "@/components/Chat";
import { useEffect } from "react";
import './globals.css';

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "600", "900"],
  variable: "--font-inter",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-work-sans",
});

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-sora",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(() => {
    const disableRightClick = (event: MouseEvent) => {
      event.preventDefault();
    };
    document.addEventListener("contextmenu", disableRightClick);
    return () => document.removeEventListener("contextmenu", disableRightClick);
  }, []);

  return (
    <html lang="en">
      <body className={`${inter.variable} ${workSans.variable} ${sora.variable} antialiased`}>
        <Provider store={store}>
          <ApolloWrapper>
            <ClientHeader />
            <Contact />
            {children}
            <div><Chat /></div>
            <Footer />
          </ApolloWrapper>
        </Provider>
      </body>
    </html>
  );
}
