'use client';

import ClientHeader from "@/components/ClientHeader";
import { ApolloWrapper } from "@/lib/ApolloWrapper";
import { Work_Sans } from "next/font/google";
import Contact from "@/components/Contact";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Sora } from "next/font/google";
import { Provider } from 'react-redux';
import { store } from '@/redux/store';
import Chat from "@/components/Chat";
import { useEffect } from "react";
import './globals.css';

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "600", "900"],
  variable: "--font-inter",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-work-sans",
});

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-sora",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(() => {
    const disableRightClick = (event: MouseEvent) => {
      event.preventDefault();
    };
    document.addEventListener("contextmenu", disableRightClick);
    return () => document.removeEventListener("contextmenu", disableRightClick);
  }, []);

  return (
    <html lang="en">
      <body className={`${inter.variable} ${workSans.variable} ${sora.variable} antialiased`}>
        <Provider store={store}>
          <ApolloWrapper>
            <ClientHeader />
            <span className="absolute text-transparent -z-50">exhibition stand, exhibition stand contractors, exhibition stand builders, exhibition stand design, exhibition stand designer, exhibition stand contractors in dubai, exhibition stand builders in dubai, exhibition stand design dubai, exhibition stand designer dubai, exhibition stand contractors abu dhabi, exhibition stand builders abu dhabi, exhibition stand design abu dhabi, exhibition stand designer abu dhabi, event management, event management dubai, event management abu dhabi, event planning, event planning dubai, event planning abu dhabi, event production, event production dubai, event production abu dhabi, interior fit out, commercial interior fit out, commercial interior fit out dubai, commercial interior fit out abu dhabi, branding, stand branding, stand branding dubai, stand branding abu dhabi, exhibition booth, exhibition booth design, exhibition booth builders, exhibition booth contractors, exhibition booth dubai, exhibition booth abu dhabi, trade show, trade show stand, trade show booth, trade show dubai, trade show abu dhabi, custom exhibition stand, modular exhibition stand, portable exhibition stand, exhibition graphics, exhibition display, exhibition display dubai, exhibition display abu dhabi, exhibition services, exhibition services dubai, exhibition services abu dhabi, event services, event services dubai, event services abu dhabi, event solutions, event solutions dubai, event solutions abu dhabi, event support, event support dubai, event support abu dhabi, exhibition installation, exhibition installation dubai, exhibition installation abu dhabi, exhibition dismantling, exhibition dismantling dubai, exhibition dismantling abu dhabi, exhibition logistics, exhibition logistics dubai, exhibition logistics abu dhabi, exhibition project management, exhibition project management dubai, exhibition project management abu dhabi, exhibition contractor, exhibition contractor dubai, exhibition contractor abu dhabi, exhibition builder, exhibition builder dubai, exhibition builder abu dhabi, exhibition designer, exhibition designer dubai, exhibition designer abu dhabi, exhibition supplier, exhibition supplier dubai, exhibition supplier abu dhabi, event contractor, event contractor dubai, event contractor abu dhabi, event builder, event builder dubai, event builder abu dhabi, event designer, event designer dubai, event designer abu dhabi, event supplier, event supplier dubai, event supplier abu dhabi, exhibition stand rental, exhibition stand rental dubai, exhibition stand rental abu dhabi, exhibition stand hire, exhibition stand hire dubai, exhibition stand hire abu dhabi, exhibition stand fabrication, exhibition stand fabrication dubai, exhibition stand fabrication abu dhabi, exhibition stand setup, exhibition stand setup dubai, exhibition stand setup abu dhabi, exhibition stand removal, exhibition stand removal dubai, exhibition stand removal abu dhabi, exhibition stand storage, exhibition stand storage dubai, exhibition stand storage abu dhabi, exhibition stand maintenance, exhibition stand maintenance dubai, exhibition stand maintenance abu dhabi, exhibition stand refurbishment, exhibition stand refurbishment dubai, exhibition stand refurbishment abu dhabi, exhibition stand lighting, exhibition stand lighting dubai, exhibition stand lighting abu dhabi, exhibition stand audio visual, exhibition stand audio visual dubai, exhibition stand audio visual abu dhabi, exhibition stand flooring, exhibition stand flooring dubai, exhibition stand flooring abu dhabi, exhibition stand furniture, exhibition stand furniture dubai, exhibition stand furniture abu dhabi, exhibition stand graphics, exhibition stand graphics dubai, exhibition stand graphics abu dhabi, exhibition stand signage, exhibition stand signage dubai, exhibition stand signage abu dhabi, exhibition stand printing, exhibition stand printing dubai, exhibition stand printing abu dhabi, exhibition stand marketing, exhibition stand marketing dubai, exhibition stand marketing abu dhabi, exhibition stand promotion, exhibition stand promotion dubai, exhibition stand promotion abu dhabi, exhibition stand management, exhibition stand management dubai, exhibition stand management abu dhabi, exhibition stand support, exhibition stand support dubai, exhibition stand support abu dhabi, exhibition stand consultation, exhibition stand consultation dubai, exhibition stand consultation abu dhabi, exhibition stand planning, exhibition stand planning dubai, exhibition stand planning abu dhabi, exhibition stand solutions, exhibition stand solutions dubai, exhibition stand solutions abu dhabi, exhibition stand company, exhibition stand company dubai, exhibition stand company abu dhabi, exhibition stand agency, exhibition stand agency dubai, exhibition stand agency abu dhabi, exhibition stand expert, exhibition stand expert dubai, exhibition stand expert abu dhabi, exhibition stand specialist, exhibition stand specialist dubai, exhibition stand specialist abu dhabi, exhibition stand professional, exhibition stand professional dubai, exhibition stand professional abu dhabi, exhibition stand consultant, exhibition stand consultant dubai, exhibition stand consultant abu dhabi, exhibition stand organizer, exhibition stand organizer dubai, exhibition stand organizer abu dhabi, exhibition stand provider, exhibition stand provider dubai, exhibition stand provider abu dhabi, exhibition stand supplier, exhibition stand supplier dubai, exhibition stand supplier abu dhabi, xess events, xess events dubai, xess events abu dhabi</span>
            <Contact />
            {children}
            <div><Chat /></div>
            <Footer />
          </ApolloWrapper>
        </Provider>
      </body>
    </html>
  );
}
